package constant

const (
	TRANSACTION_INSTRUCTION_TYPE_IMMEDIATE            = "IMMEDIATE"
	TRANSACTION_INSTRUCTION_TYPE_STANDING_INSTRUCTION = "STANDING_INSTRUCTION"
)

var TRANSACTION_INSTRUCTION_TYPES = map[string]bool{
	TRANSACTION_INSTRUCTION_TYPE_IMMEDIATE:            true,
	TRANSACTION_INSTRUCTION_TYPE_STANDING_INSTRUCTION: true,
}
