package constant

const (
	TRANSFER_RECORD_STATUS_AWAITING_APPROVAL = "AWAITING_APPROVAL"
	TRANSFER_RECORD_STATUS_APPROVED          = "APPROVED"
	TRANSFER_RECORD_STATUS_REJECTED          = "REJECTED"
)

var TRANSFER_RECORD_STATUSES = map[string]bool{
	TRANSFER_RECORD_STATUS_AWAITING_APPROVAL: true,
	TRANSFER_RECORD_STATUS_APPROVED:          true,
	TRANSFER_RECORD_STATUS_REJECTED:          true,
}
